# Generated by Django 3.2.9 on 2021-12-10 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shuttle_output_buffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kecepatan_maks', models.FloatField()),
                ('waktu_loading', models.FloatField()),
                ('waktu_unloading', models.FloatField()),
                ('cell_to_output_buffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rack.output_buffer')),
                ('shuttle_to_output_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rack.cell')),
                ('shuttle_to_output_y', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rack.cell')),
            ],
        ),
        migrations.CreateModel(
            name='shuttle_input_buffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kecepatan_maks', models.FloatField()),
                ('waktu_loading', models.FloatField()),
                ('waktu_unloading', models.FloatField()),
                ('input_buffer_to_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rack.input_buffer')),
                ('shuttle_input_to_cell_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rack.cell')),
                ('shuttle_input_to_cell_y', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rack.cell')),
            ],
        ),
    ]
